swagger: '2.0'
info:
  title: ShopSphere Backend APIs
  description: API Gateway for Products, Inventory, Orders
  version: 1.0.0
paths:
  /products:
    get:
      operationId: getProducts
      x-google-backend:
        address: https://products-624960109864.us-central1.run.app
      responses:
        '200':
          description: A successful response

  /inventory:
    get:
      operationId: getInventory
      x-google-backend:
        address: https://inventory-624960109864.us-central1.run.app
      responses:
        '200':
          description: A successful response

  /orders:
    get:
      operationId: getOrders
      x-google-backend:
        address: https://orders-624960109864.us-central1.run.app
      responses:
        '200':
          description: A successful response

host: shopsphere-12.gateway.dev
